server:
  port: 8080

app:
  secret-key: szs-mj-practice-very-long-secret-key-for-jwt-signing-123456789

spring:
  datasource:
    url: jdbc:h2:mem:szs
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

external:
  scrap:
    base-url: https://codetest-v4.3o3.co.kr
    api-key: eUdJijcuJgmN/xtBKyK2bg==