server:
  port: 8080

app:
  secret-key: szs!mjseo1234!@#

spring:
  datasource:
    url: jdbc:h2:mem:szs
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
